version: "3"
services:
  web:
  #your image detials 
  image: adhiar/fhello:latest
  deploy:
    replicas: 5
    resources:
      limits:
      cpus: "0.1"
      memory: 50M
    restart_policy:
      condition: on-failure
    ports:
      - "4000:80"
    network:
      - webnet
networks:
  webnet:
